"""Phase 0 drift guard, agent-cloud side (GAP_ASSESSMENT_S9 §3).

agent-cloud is a separate service and cannot import the api ORM models, but it
CAN prove that:

  1. `app.approvals` sources every write vocabulary from the shared generated
     contract (`app/contracts/agentcloud_write_vocab.json`), not hand literals.
  2. The vendored agent-cloud copy is byte-identical to the vendored api copy
     (the single source of truth generated by scripts/gen_write_vocab.py).

Test (2) is what actually catches drift between the two services: if either
copy is regenerated or edited independently, the bytes diverge and this fails.
"""

from __future__ import annotations

import json
from pathlib import Path

from app import approvals
from app.contracts import write_vocab

# tests/ -> agent-cloud/ -> repo root
REPO_ROOT = Path(__file__).resolve().parents[2]
AC_COPY = REPO_ROOT / "agent-cloud" / "app" / "contracts" / "agentcloud_write_vocab.json"
API_COPY = REPO_ROOT / "api" / "app" / "contracts" / "agentcloud_write_vocab.json"


def test_approvals_vocab_comes_from_contract():
    vocab = write_vocab()
    assert approvals.VALID_PHASES == vocab["project_phases"]
    assert approvals.VALID_PROJECT_STATUSES == vocab["project_statuses"]
    assert approvals.VALID_ENTRY_TYPES == vocab["log_entry_types"]
    assert approvals.VALID_DEAL_STAGES == vocab["deal_stages"]
    assert approvals.VALID_REQUEST_STATUSES == vocab["request_action_statuses"]


def test_vendored_copy_matches_api_copy_byte_for_byte():
    """The cross-service coherence guarantee: both vendored copies are equal.

    Skips only if the api tree isn't present alongside (e.g. a slimmed
    single-service checkout); in the monorepo it must match exactly.
    """
    assert AC_COPY.exists(), f"missing {AC_COPY}"
    if not API_COPY.exists():
        import pytest

        pytest.skip("api tree not present in this checkout")
    assert AC_COPY.read_bytes() == API_COPY.read_bytes()


def test_contract_is_wellformed():
    data = json.loads(AC_COPY.read_text())
    assert data["contract_version"] >= 1
    assert set(data["vocabularies"]) == {
        "project_phases",
        "phase_order",
        "project_statuses",
        "log_entry_types",
        "deal_stages",
        "request_action_statuses",
    }
