#!/usr/bin/env python3
"""Generate the shared agent-cloud write-vocabulary contract (Phase 0, GAP §3).

Single source of truth: the api canonical ORM models
(`api/app/models_projects.py`, `api/app/models_pipeline.py`,
`api/app/models_requests.py`). This script reads those enums and emits ONE
authoritative JSON contract, then vendors a byte-identical copy into BOTH
services' own trees, because each service is built/deployed from its own
Docker context and cannot import the other's Python at runtime:

  - api/app/contracts/agentcloud_write_vocab.json      (api build context = api/)
  - agent-cloud/app/contracts/agentcloud_write_vocab.json  (build context = agent-cloud/)

Both files are generated, never hand-edited. `test_write_vocab_contract.py`
on each side fails the build if the vendored copy drifts from the api
canonical models (the drift guard that replaces the old hand-sync comment).

Usage:
    python scripts/gen_write_vocab.py            # regenerate both vendored copies
    python scripts/gen_write_vocab.py --check    # exit 1 if either copy is stale

The `--check` mode is what CI / the contract tests call.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_ROOT = REPO_ROOT / "api"

# Vendored destinations (one per service build context).
DEST_PATHS = (
    API_ROOT / "app" / "contracts" / "agentcloud_write_vocab.json",
    REPO_ROOT / "agent-cloud" / "app" / "contracts" / "agentcloud_write_vocab.json",
)

CONTRACT_VERSION = 1


def _load_canonical() -> dict:
    """Import the api canonical enums and assemble the contract payload.

    We import lazily (inside the function) so the module import path is only
    needed when actually generating — the vendored JSON at runtime needs no
    api import.
    """
    if str(API_ROOT) not in sys.path:
        sys.path.insert(0, str(API_ROOT))

    from app.models_pipeline import VALID_DEAL_STAGES  # noqa: E402
    from app.models_projects import (  # noqa: E402
        VALID_ENTRY_TYPES,
        VALID_PHASES,
        VALID_STATUSES,
    )
    from app.models_requests import VALID_REQUEST_ACTION_STATUSES  # noqa: E402

    # PHASE_ORDER is the advance-phase ordering; canonical copy lives on the
    # api project routes / executor. It MUST be a permutation of VALID_PHASES.
    phase_order = list(VALID_PHASES)

    contract = {
        "_generated": (
            "DO NOT EDIT. Generated by scripts/gen_write_vocab.py from the api "
            "canonical ORM models (api/app/models_projects.py, models_pipeline.py, "
            "models_requests.py). Run `python scripts/gen_write_vocab.py` to "
            "regenerate. The per-service contract tests fail if this drifts."
        ),
        "contract_version": CONTRACT_VERSION,
        "vocabularies": {
            "project_phases": list(VALID_PHASES),
            "phase_order": phase_order,
            "project_statuses": list(VALID_STATUSES),
            "log_entry_types": list(VALID_ENTRY_TYPES),
            "deal_stages": list(VALID_DEAL_STAGES),
            "request_action_statuses": list(VALID_REQUEST_ACTION_STATUSES),
        },
    }
    return contract


def _serialize(contract: dict) -> str:
    # Stable, sorted, trailing newline — so byte comparison across copies is exact.
    return json.dumps(contract, indent=2, sort_keys=True) + "\n"


def content_hash(contract: dict) -> str:
    return hashlib.sha256(_serialize(contract).encode("utf-8")).hexdigest()


def generate(check: bool = False) -> int:
    contract = _load_canonical()
    payload = _serialize(contract)
    stale: list[Path] = []
    for dest in DEST_PATHS:
        current = dest.read_text() if dest.exists() else None
        if current != payload:
            stale.append(dest)
            if not check:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(payload)
    if check:
        if stale:
            rels = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
            print(f"STALE write-vocab contract: {rels}", file=sys.stderr)
            print("Run: python scripts/gen_write_vocab.py", file=sys.stderr)
            return 1
        print("write-vocab contract is up to date")
        return 0
    if stale:
        rels = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(f"regenerated: {rels}")
    else:
        print("write-vocab contract already current (no changes)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if a vendored copy is stale (do not write)",
    )
    args = ap.parse_args()
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
